update conda glib/fontconfig pkgs on linux
The `0` build versions of these packages appear to have been recently
removed from the public conda repositories.  The OSX versions of these
packages appear to have not been rebuilt.

    PackageNotFoundError: Package not found: '' Packages missing in current
    linux-64 channels:

      - fontconfig 2.12.1 0
      - glib 2.50.2 0